// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oiuhhfuyfpsfuvctkexd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pdWhoZnV5ZnBzZnV2Y3RrZXhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMTA3NDUsImV4cCI6MjA2NDY4Njc0NX0.-_Qvq8Saezww0lR7DZ0_9Fccct-sgrDrlZ8ITP2vARw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);